#ifndef XW_FLIGHT_GATE_H
#define XW_FLIGHT_GATE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

enum {
	GATE_COURSE_FILENAME_SCAN_LIMIT = 127,
	GATE_COURSE_HALF_TURN = 128,
	GATE_COURSE_FIRST_CHECKPOINT_FLAGS = 0x15,
	GATE_COURSE_CHECKPOINTS_REMAINING = 109
};

enum {
	GATE_DRAW_ORDER_COUNT = 11,
	GATE_CHECKPOINT_STATE_MASK = 3,
	GATE_RENDER_REFERENCE_BASE = 0x4000,
	GATE_LOW_DETAIL_DRAW_DISTANCE = 131072,
	GATE_MEDIUM_DETAIL_DRAW_DISTANCE = 196608,
	GATE_NEAR_DRAW_DISTANCE = 65536,
	GATE_SIMPLE_MESH_COUNT = 2,
	GATE_BLINK_PERIOD = 2000,
	GATE_BLINK_ON_TICKS = 1000,
	GATE_OBJECT_TYPE_203 = 203,
	GATE_OBJECT_TYPE_204 = 204,
	GATE_OBJECT_TYPE_205 = 205,
	GATE_OBJECT_TYPE_206 = 206,
	GATE_OBJECT_TYPE_207 = 207,
	GATE_OBJECT_TYPE_208 = 208,
	GATE_OBJECT_TYPE_209 = 209,
	GATE_OBJECT_TYPE_210 = 210
};

enum {
	GATE_BONUS_BACKGROUND_COLOR = 0x19,
	GATE_BONUS_TEXT_COLOR = 0x49,
	GATE_BONUS_TIMER_DIGITS = 2,
	GATE_BONUS_VALUE_DIGITS = 5
};

enum { GATE_SCORE_DIVISOR_COUNT = 9, GATE_DECIMAL_MAX_DIGIT = 9 };

enum { GATE_POSE_HISTORY_COUNT = 4 };

enum {
	GATE_GUN_PERIOD = 59,
	GATE_GUN_RANGE = 0x4000,
	GATE_GUN_ARMED = 0x80,
	GATE_GUN_COUNT = 6,
	GATE_GUN_FIRST_MESH = 4,
	GATE_GUN_MUZZLE_OFFSET = 64,
	GATE_COORDINATE_SCALE = 256,
	GATE_ANGLE_SHIFT = 8,
	GATE_GUN_MEDIUM_LEVEL = 10,
	GATE_GUN_HIGH_LEVEL = 11,
	GATE_GUN_LOW_RANDOM_MASK = 7,
	GATE_GUN_MEDIUM_RANDOM_MASK = 3,
	GATE_GUN_HIGH_RANDOM_MASK = 1,
	GATE_GUN_LEAD_SHIFT = 14,
	GATE_GUN_LEAD_RANDOM_MASK = 3,
	GATE_GUN_ACCURACY_LEVEL = 9,
	GATE_GUN_DISTANCE_LIMIT = 0x10000,
	GATE_GUN_MAX_ACCURACY = 0xFFFF,
	GATE_GUN_SLOW_SPEED = 50,
	GATE_GUN_FAST_SPEED = 275,
	GATE_GUN_FAST_ACCURACY = 0x2000,
	GATE_GUN_SPEED_ACCURACY_BASE = 0x31FF,
	GATE_GUN_SCATTER_OFFSET = 256,
	GATE_GUN_SCATTER_MASK = 0x3FF,
	GATE_GUN_SCATTER_SIGN = 0x8000,
	GATE_GUN_SOURCE_REF = 0x4000,
	GATE_GUN_IFF = 1
};

enum {
	GATE_LOW_PANEL_WIDTH = 60,
	GATE_HIGH_PANEL_WIDTH = 132,
	GATE_LOW_PANEL_HEIGHT = 41,
	GATE_HIGH_PANEL_HEIGHT = 91,
	GATE_LOW_LEVEL_LABEL_XOFFSET = 12,
	GATE_HIGH_LEVEL_LABEL_XOFFSET = 24,
	GATE_LOW_LEVEL_VALUE_XOFFSET = 40,
	GATE_HIGH_LEVEL_VALUE_XOFFSET = 80,
	GATE_LOW_LINE_SPACING = 7,
	GATE_HIGH_LINE_SPACING = 14,
	GATE_LOW_COUNTER_XOFFSET = 48,
	GATE_HIGH_COUNTER_XOFFSET = 96,
	GATE_LOW_SCORE_XOFFSET = 36,
	GATE_HIGH_SCORE_XOFFSET = 78,
	GATE_LOW_BONUS_CLIP_RIGHT = 320,
	GATE_HIGH_BONUS_CLIP_RIGHT = 640,
	GATE_LOW_BONUS_CLIP_BOTTOM = 200,
	GATE_HIGH_BONUS_CLIP_BOTTOM = 480,
	GATE_LOW_BONUS_CLIP_TOP = 190,
	GATE_HIGH_BONUS_CLIP_TOP = 456,
	GATE_LOW_BONUS_VALUE_X = 252,
	GATE_HIGH_BONUS_VALUE_X = 510,
	GATE_LOW_BONUS_TIMER_X = 198,
	GATE_HIGH_BONUS_TIMER_X = 400,
	GATE_LOW_BONUS_TEXT_Y = 191,
	GATE_HIGH_BONUS_TEXT_Y = 458,
	GATE_PANEL_LEFT_INSET = 4,
	GATE_PANEL_TOP_INSET = 1,
	GATE_PANEL_BACKGROUND_COLOR = 0x1D,
	GATE_LEVEL_LABEL_COLOR = 0x44,
	GATE_LEVEL_VALUE_COLOR = 0x43,
	GATE_CHECKPOINT_LABEL_COLOR = 0x42,
	GATE_CHECKPOINT_VALUE_COLOR = 0x41,
	GATE_TARGET_LABEL_COLOR = 0x48,
	GATE_TARGET_VALUE_COLOR = 0x47,
	GATE_SCORE_LABEL_COLOR = 0x46,
	GATE_SCORE_VALUE_COLOR = 0x45,
	GATE_LEVEL_DIGITS = 2,
	GATE_COUNTER_WIDTH = 4,
	GATE_SCORE_WIDTH = 7,
	GATE_REMAINING_ROW = 1,
	GATE_MISSED_ROW = 2,
	GATE_PASSED_ROW = 3,
	GATE_TARGET_ROW = 4,
	GATE_SCORE_ROW = 5
};

enum {
	GATE_OBJECT_TYPE_202 = 202,
	GATE_TYPE_202_HALF_WIDTH = 1920,
	GATE_TYPE_202_HALF_HEIGHT = 2259,
	GATE_HALF_WIDTH = 2400,
	GATE_HALF_HEIGHT = 8320,
	GATE_BEVEL_START_HEIGHT = 7520,
	GATE_BEVEL_SLOPE = 3,
	GATE_FRACTION_DIVIDEND_SHIFT = 16,
	GATE_FRACTION_SCALE_SHIFT = 1,
	GATE_INTERPOLATION_SHIFT = 15
};

enum {
	GATE_COLLISION_RANGE = 0x4000,
	GATE_TARGET_DEPTH = 624,
	GATE_CHECKPOINT_DEPTH = 1278,
	GATE_CHECKPOINT_FRONT = 400,
	GATE_FIRST_CHECKPOINT_MESH = 1,
	GATE_CHECKPOINT_MESH_COUNT = 3,
	GATE_CHECKPOINT_PAIR_BITS = 2,
	GATE_CHECKPOINT_CURRENT = 1,
	GATE_CHECKPOINT_COMPLETE = 2,
	GATE_CHECKPOINT_ALL_COMPLETE = 0x2A,
	GATE_NO_CHECKPOINT = 0xFFFF,
	GATE_TARGET_SCORE = 25,
	GATE_TARGET_SECONDS = 2,
	GATE_CHECKPOINT_SCORE = 100,
	GATE_MISSED_CHECKPOINT_SECONDS = 15,
	GATE_BONUS_POINTS_PER_SECOND = 10,
	GATE_BONUS_SOUND_INTERVAL = 100,
	GATE_BONUS_WAIT_TICKS = 4,
	GATE_CHECKPOINT_SOUND = 36,
	GATE_BONUS_SOUND = 29,
	GATE_TIMEOUT_EXIT_REASON = 1,
	GATE_IMPACT_PLANE_OFFSET = 48,
	GATE_IMPACT_LARGE_SCALE = 2
};

extern int g_provingGroundsScoreDecimalDivisors[GATE_SCORE_DIVISOR_COUNT];
extern int g_provingGroundsPanelHeight;
extern int g_provingGroundsBonusTextY;
extern int g_provingGroundsBonusTimerX;
extern int g_provingGroundsLevelLabelXOffset;
extern int g_provingGroundsPanelWidth;
extern int g_provingGroundsLevelValueXOffset;
extern int g_provingGroundsBonusClipTop;
extern int g_provingGroundsCounterXOffset;
extern int g_provingGroundsLineSpacing;
extern int g_provingGroundsBonusValueX;
extern int g_provingGroundsScoreXOffset;
extern int g_provingGroundsBonusClipRight;
extern int g_provingGroundsBonusClipBottom;
extern uint16_t g_gateGunTimer;
extern int g_gateIntersectionX;
extern int g_gateIntersectionZ;
extern uint16_t g_provingGroundsRenderCheckpointState;
extern uint16_t g_provingGroundsCheckpointBlinkTicks;
extern int16_t g_gatePreviousRoll[GATE_POSE_HISTORY_COUNT];
extern int16_t g_gatePreviousPitch[GATE_POSE_HISTORY_COUNT];
extern int16_t g_gatePreviousYaw[GATE_POSE_HISTORY_COUNT];
extern int g_gatePreviousZ[GATE_POSE_HISTORY_COUNT];
extern int g_gatePreviousX[GATE_POSE_HISTORY_COUNT];
extern int g_gatePreviousY[GATE_POSE_HISTORY_COUNT];
extern int16_t g_provingGroundsMeshDrawOrder[GATE_DRAW_ORDER_COUNT];

/* Declarations follow ascending original IDB address. */

/* 0x40E320 */
void gate_savegatelastpos(void);

/* 0x40E400 */
void gate_DrawCourseObject(uint16_t missionObjectIndex);

/* 0x40E7C0 */
int16_t gate_ProcessCourseCollision(uint16_t objectIndex);

/* 0x40F4D0 */
int16_t gate_TestGatePlaneCollision(uint16_t objectType);

/* 0x40F660 */
void gate_updategateguns(void);

/* 0x40FD40 */
void gate_LoadNextCourse(void);

/* 0x40FFB0 */
void gate_trainingupdatecrt(int16_t x, int16_t y);

/* 0x410390 */
void gate_outdnum(int score, uint16_t width, uint16_t minDigits);

/* 0x410410 */
void gate_updatebonuspoints(void);

#ifdef __cplusplus
}
#endif

#endif
