#ifndef XW_FRONTEND_INFLIGHT_OPTIONS_H
#define XW_FRONTEND_INFLIGHT_OPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "xw/landru_config.h"

#include <landru/input.h>
#include <landru/rect.h>
#include <stddef.h>
#include <stdint.h>
#include <xw/frontend/shell.h>

struct XwShellContext;

enum {
	INFLIGHT_OPTIONS_GENERAL_PAGE = 0,
	INFLIGHT_OPTIONS_GRAPHICS_PAGE = 1,
	INFLIGHT_OPTIONS_SECTION_LEFT = 8,
	INFLIGHT_OPTIONS_SECTION_RIGHT = 312,
	INFLIGHT_OPTIONS_SECTION_TOP = 27,
	INFLIGHT_OPTIONS_SECTION_BOTTOM = 89,
	INFLIGHT_OPTIONS_SECTION_STEP = 63,
	INFLIGHT_OPTIONS_GRAPHICS_SECTION_HEIGHT = 85,
	INFLIGHT_OPTIONS_GENERAL_MIDDLE_HEIGHT = 22,
	INFLIGHT_OPTIONS_GENERAL_BOTTOM_STEP = 23,
	INFLIGHT_OPTIONS_GENERAL_BOTTOM_HEIGHT = 62,
	INFLIGHT_OPTIONS_UPPER_HIGHLIGHT = 61,
	INFLIGHT_OPTIONS_UPPER_SHADOW = 63,
	INFLIGHT_OPTIONS_UPPER_FILL = 62,
	INFLIGHT_OPTIONS_MIDDLE_HIGHLIGHT = 50,
	INFLIGHT_OPTIONS_MIDDLE_SHADOW = 48,
	INFLIGHT_OPTIONS_MIDDLE_FILL = 49,
	INFLIGHT_OPTIONS_LOWER_HIGHLIGHT = 54,
	INFLIGHT_OPTIONS_LOWER_SHADOW = 52,
	INFLIGHT_OPTIONS_LOWER_FILL = 53,
	INFLIGHT_OPTIONS_STARFIGHTER_LABEL_X = 46,
	INFLIGHT_OPTIONS_STARFIGHTER_LABEL_Y = 44,
	INFLIGHT_OPTIONS_STARSHIP_LABEL_X = 63,
	INFLIGHT_OPTIONS_STARSHIP_LABEL_Y = 58,
	INFLIGHT_OPTIONS_DEATH_STAR_LABEL_X = 47,
	INFLIGHT_OPTIONS_DEATH_STAR_LABEL_Y = 72
};

enum {
	INFLIGHT_OPTIONS_PAGE_COUNT = 2,
	INFLIGHT_OPTIONS_TITLE_CAPACITY = 32,
	INFLIGHT_OPTIONS_TITLE_ID = 0,
	INFLIGHT_OPTIONS_PREVIOUS_ID = 1,
	INFLIGHT_OPTIONS_NEXT_ID = 2,
	INFLIGHT_OPTIONS_RESUME_ID = 3,
	INFLIGHT_OPTIONS_ESCAPE_ID = 4,
	INFLIGHT_OPTIONS_TITLE_FONT = 0,
	INFLIGHT_OPTIONS_TITLE_COLOR = 15
};

enum {
	INFLIGHT_OPTIONS_MUSIC_VOLUME_ID = 1,
	INFLIGHT_OPTIONS_SOUND_VOLUME_ID = 3,
	INFLIGHT_OPTIONS_FIRST_DETAIL_ID = 5,
	INFLIGHT_OPTIONS_LAST_DETAIL_ID = 7,
	INFLIGHT_OPTIONS_SLIDER_INSET = 2,
	INFLIGHT_OPTIONS_SLIDER_SEGMENT_WIDTH = 4,
	INFLIGHT_OPTIONS_SLIDER_COLOR = 62,
	INFLIGHT_OPTIONS_MOUSE_RELEASE = 3,
	INFLIGHT_OPTIONS_VOLUME_STEP_WIDTH = 5,
	INFLIGHT_OPTIONS_VOLUME_MAX = 16,
	INFLIGHT_OPTIONS_DETAIL_STEP_WIDTH = 5,
	INFLIGHT_OPTIONS_DETAIL_MAX = 12
};

enum {
	INFLIGHT_OPTIONS_FOCUS_COLUMNS = 5,
	INFLIGHT_OPTIONS_PAGE0_FOCUS_ROWS = 9,
	INFLIGHT_OPTIONS_PAGE1_FOCUS_ROWS = 10,
	INFLIGHT_OPTIONS_PAGE0_FOCUS_COUNT = INFLIGHT_OPTIONS_FOCUS_COLUMNS * INFLIGHT_OPTIONS_PAGE0_FOCUS_ROWS,
	INFLIGHT_OPTIONS_PAGE1_FOCUS_COUNT = INFLIGHT_OPTIONS_FOCUS_COLUMNS * INFLIGHT_OPTIONS_PAGE1_FOCUS_ROWS
};

enum {
	INFLIGHT_OPTIONS_BACKDROPS_ID = 0,
	INFLIGHT_OPTIONS_DEBRIS_ID = 1,
	INFLIGHT_OPTIONS_STARFIELD_ID = 2,
	INFLIGHT_OPTIONS_INTERLACE_ID = 3,
	INFLIGHT_OPTIONS_ENGINE_GLOW_ID = 4,
	INFLIGHT_OPTIONS_STARFIGHTER_DETAIL_ID = 5,
	INFLIGHT_OPTIONS_STARSHIP_DETAIL_ID = 6,
	INFLIGHT_OPTIONS_DEATH_STAR_DETAIL_ID = 7,
	INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT = 2,
	INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY = 32
};

enum {
	INFLIGHT_OPTIONS_MUSIC_ENABLED_ID = 0,
	INFLIGHT_OPTIONS_SOUND_ENABLED_ID = 2,
	INFLIGHT_OPTIONS_DISK_CACHE_ID = 4,
	INFLIGHT_OPTIONS_INCREASE_CACHE_ID = 5,
	INFLIGHT_OPTIONS_DECREASE_CACHE_ID = 6,
	INFLIGHT_OPTIONS_UNLIMITED_WEAPONS_ID = 7,
	INFLIGHT_OPTIONS_INVULNERABILITY_ID = 8,
	INFLIGHT_OPTIONS_COLLISIONS_ID = 9,
	INFLIGHT_OPTIONS_DIGITAL_SOUND_ID = 10,
	INFLIGHT_OPTIONS_SPEECH_ID = 11,
	INFLIGHT_OPTIONS_CACHE_STEP_KB = 32,
	INFLIGHT_OPTIONS_CACHE_MIN_KB = 32,
	INFLIGHT_OPTIONS_CACHE_MAX_KB = 2048,
	INFLIGHT_OPTIONS_CACHE_LABEL_CAPACITY = 40,
	INFLIGHT_OPTIONS_CACHE_SUFFIX_CAPACITY = 12
};

enum {
	INFLIGHT_OPTIONS_INITIAL_FOCUS = 8,
	INFLIGHT_OPTIONS_INITIAL_MOUSE_X = 270,
	INFLIGHT_OPTIONS_INITIAL_MOUSE_Y = 325,
	INFLIGHT_OPTIONS_ALIGN_CENTER = 1,
	INFLIGHT_OPTIONS_DEATH_STAR_FRAME_LEFT = 180,
	INFLIGHT_OPTIONS_DEATH_STAR_FRAME_TOP = 133,
	INFLIGHT_OPTIONS_DEATH_STAR_FRAME_RIGHT = 243,
	INFLIGHT_OPTIONS_DEATH_STAR_FRAME_BOTTOM = 145,
	INFLIGHT_OPTIONS_STARSHIP_FRAME_LEFT = 180,
	INFLIGHT_OPTIONS_STARSHIP_FRAME_TOP = 119,
	INFLIGHT_OPTIONS_STARSHIP_FRAME_RIGHT = 243,
	INFLIGHT_OPTIONS_STARSHIP_FRAME_BOTTOM = 131,
	INFLIGHT_OPTIONS_STARFIGHTER_FRAME_LEFT = 180,
	INFLIGHT_OPTIONS_STARFIGHTER_FRAME_TOP = 105,
	INFLIGHT_OPTIONS_STARFIGHTER_FRAME_RIGHT = 243,
	INFLIGHT_OPTIONS_STARFIGHTER_FRAME_BOTTOM = 117,
	INFLIGHT_OPTIONS_ENGINE_GLOW_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_ENGINE_GLOW_FRAME_TOP = 85,
	INFLIGHT_OPTIONS_ENGINE_GLOW_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_ENGINE_GLOW_FRAME_BOTTOM = 103,
	INFLIGHT_OPTIONS_INTERLACE_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_INTERLACE_FRAME_TOP = 65,
	INFLIGHT_OPTIONS_INTERLACE_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_INTERLACE_FRAME_BOTTOM = 83,
	INFLIGHT_OPTIONS_STARFIELD_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_STARFIELD_FRAME_TOP = 42,
	INFLIGHT_OPTIONS_STARFIELD_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_STARFIELD_FRAME_BOTTOM = 60,
	INFLIGHT_OPTIONS_DEBRIS_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_DEBRIS_FRAME_TOP = 22,
	INFLIGHT_OPTIONS_DEBRIS_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_DEBRIS_FRAME_BOTTOM = 40,
	INFLIGHT_OPTIONS_BACKDROPS_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_BACKDROPS_FRAME_TOP = 2,
	INFLIGHT_OPTIONS_BACKDROPS_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_BACKDROPS_FRAME_BOTTOM = 20,
	INFLIGHT_OPTIONS_COLLISIONS_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_COLLISIONS_FRAME_TOP = 128,
	INFLIGHT_OPTIONS_COLLISIONS_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_COLLISIONS_FRAME_BOTTOM = 146,
	INFLIGHT_OPTIONS_INVULNERABILITY_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_INVULNERABILITY_FRAME_TOP = 108,
	INFLIGHT_OPTIONS_INVULNERABILITY_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_INVULNERABILITY_FRAME_BOTTOM = 126,
	INFLIGHT_OPTIONS_WEAPONS_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_WEAPONS_FRAME_TOP = 88,
	INFLIGHT_OPTIONS_WEAPONS_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_WEAPONS_FRAME_BOTTOM = 106,
	INFLIGHT_OPTIONS_DECREASE_CACHE_FRAME_LEFT = 254,
	INFLIGHT_OPTIONS_DECREASE_CACHE_FRAME_TOP = 65,
	INFLIGHT_OPTIONS_DECREASE_CACHE_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_DECREASE_CACHE_FRAME_BOTTOM = 83,
	INFLIGHT_OPTIONS_INCREASE_CACHE_FRAME_LEFT = 204,
	INFLIGHT_OPTIONS_INCREASE_CACHE_FRAME_TOP = 65,
	INFLIGHT_OPTIONS_INCREASE_CACHE_FRAME_RIGHT = 250,
	INFLIGHT_OPTIONS_INCREASE_CACHE_FRAME_BOTTOM = 83,
	INFLIGHT_OPTIONS_DISK_CACHE_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_DISK_CACHE_FRAME_TOP = 65,
	INFLIGHT_OPTIONS_DISK_CACHE_FRAME_RIGHT = 200,
	INFLIGHT_OPTIONS_DISK_CACHE_FRAME_BOTTOM = 83,
	INFLIGHT_OPTIONS_SPEECH_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_SPEECH_FRAME_TOP = 42,
	INFLIGHT_OPTIONS_SPEECH_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_SPEECH_FRAME_BOTTOM = 60,
	INFLIGHT_OPTIONS_DIGITAL_SOUND_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_DIGITAL_SOUND_FRAME_TOP = 42,
	INFLIGHT_OPTIONS_DIGITAL_SOUND_FRAME_RIGHT = 148,
	INFLIGHT_OPTIONS_DIGITAL_SOUND_FRAME_BOTTOM = 60,
	INFLIGHT_OPTIONS_SOUND_VOLUME_FRAME_LEFT = 217,
	INFLIGHT_OPTIONS_SOUND_VOLUME_FRAME_TOP = 24,
	INFLIGHT_OPTIONS_SOUND_VOLUME_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_SOUND_VOLUME_FRAME_BOTTOM = 38,
	INFLIGHT_OPTIONS_SOUND_TOGGLE_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_SOUND_TOGGLE_FRAME_TOP = 22,
	INFLIGHT_OPTIONS_SOUND_TOGGLE_FRAME_RIGHT = 211,
	INFLIGHT_OPTIONS_SOUND_TOGGLE_FRAME_BOTTOM = 40,
	INFLIGHT_OPTIONS_MUSIC_VOLUME_FRAME_LEFT = 217,
	INFLIGHT_OPTIONS_MUSIC_VOLUME_FRAME_TOP = 4,
	INFLIGHT_OPTIONS_MUSIC_VOLUME_FRAME_RIGHT = 300,
	INFLIGHT_OPTIONS_MUSIC_VOLUME_FRAME_BOTTOM = 17,
	INFLIGHT_OPTIONS_MUSIC_TOGGLE_FRAME_LEFT = 4,
	INFLIGHT_OPTIONS_MUSIC_TOGGLE_FRAME_TOP = 2,
	INFLIGHT_OPTIONS_MUSIC_TOGGLE_FRAME_RIGHT = 211,
	INFLIGHT_OPTIONS_MUSIC_TOGGLE_FRAME_BOTTOM = 20,
	INFLIGHT_OPTIONS_PAGE_FRAME_LEFT = 8,
	INFLIGHT_OPTIONS_PAGE_FRAME_TOP = 27,
	INFLIGHT_OPTIONS_PAGE_FRAME_RIGHT = 312,
	INFLIGHT_OPTIONS_PAGE_FRAME_BOTTOM = 175,
	INFLIGHT_OPTIONS_ESCAPE_FRAME_LEFT = 168,
	INFLIGHT_OPTIONS_ESCAPE_FRAME_TOP = 178,
	INFLIGHT_OPTIONS_ESCAPE_FRAME_RIGHT = 312,
	INFLIGHT_OPTIONS_ESCAPE_FRAME_BOTTOM = 194,
	INFLIGHT_OPTIONS_RESUME_FRAME_LEFT = 8,
	INFLIGHT_OPTIONS_RESUME_FRAME_TOP = 178,
	INFLIGHT_OPTIONS_RESUME_FRAME_RIGHT = 152,
	INFLIGHT_OPTIONS_RESUME_FRAME_BOTTOM = 194,
	INFLIGHT_OPTIONS_NEXT_FRAME_LEFT = 296,
	INFLIGHT_OPTIONS_NEXT_FRAME_TOP = 6,
	INFLIGHT_OPTIONS_NEXT_FRAME_RIGHT = 312,
	INFLIGHT_OPTIONS_NEXT_FRAME_BOTTOM = 22,
	INFLIGHT_OPTIONS_PREVIOUS_FRAME_LEFT = 8,
	INFLIGHT_OPTIONS_PREVIOUS_FRAME_TOP = 6,
	INFLIGHT_OPTIONS_PREVIOUS_FRAME_RIGHT = 24,
	INFLIGHT_OPTIONS_PREVIOUS_FRAME_BOTTOM = 22,
	INFLIGHT_OPTIONS_TITLE_FRAME_LEFT = 28,
	INFLIGHT_OPTIONS_TITLE_FRAME_TOP = 6,
	INFLIGHT_OPTIONS_TITLE_FRAME_RIGHT = 292,
	INFLIGHT_OPTIONS_TITLE_FRAME_BOTTOM = 22,
	INFLIGHT_OPTIONS_INPUT_FRAME_LEFT = 0,
	INFLIGHT_OPTIONS_INPUT_FRAME_TOP = 0,
	INFLIGHT_OPTIONS_INPUT_FRAME_RIGHT = 320,
	INFLIGHT_OPTIONS_INPUT_FRAME_BOTTOM = 200,
	INFLIGHT_OPTIONS_CANVAS_LEFT = 0,
	INFLIGHT_OPTIONS_CANVAS_TOP = 0,
	INFLIGHT_OPTIONS_CANVAS_RIGHT = 640,
	INFLIGHT_OPTIONS_CANVAS_BOTTOM = 480
};

extern char g_inflightOptionsMusicLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsSoundLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern Input* g_inflightOptionsRootInput;
extern int g_inflightOptionsMusicContext;

extern char g_inflightOptionsDiskCacheLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
											[INFLIGHT_OPTIONS_CACHE_LABEL_CAPACITY];
extern char g_inflightOptionsCacheOffText[INFLIGHT_OPTIONS_CACHE_LABEL_CAPACITY];
extern char g_inflightOptionsCacheOnText[INFLIGHT_OPTIONS_CACHE_LABEL_CAPACITY];
extern char g_inflightOptionsWeaponsLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
										  [INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsInvulnerabilityLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
												  [INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsCollisionsLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
											 [INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsDigitalSoundLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
											   [INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsSpeechLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
										 [INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];

extern uint8_t g_flightHighDetailStarfield;
extern uint8_t g_flightBackdropsPreference;
extern uint8_t g_flightDebrisPreference;
extern int8_t g_flightMarkingsPreference;
extern uint8_t g_flightEngineGlowPreference;
extern int8_t g_flightStarfighterDetail;
extern int8_t g_flightStarshipDetail;
extern int8_t g_flightDeathStarDetail;
extern char g_inflightOptionsPageTitles[INFLIGHT_OPTIONS_PAGE_COUNT][INFLIGHT_OPTIONS_TITLE_CAPACITY];
extern char g_inflightOptionsBackdropsLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
											[INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsDebrisLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
										 [INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsStarfieldLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
											[INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsEngineGlowLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
											 [INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern char g_inflightOptionsInterlaceLabels[INFLIGHT_OPTIONS_TOGGLE_LABEL_COUNT]
											[INFLIGHT_OPTIONS_TOGGLE_LABEL_CAPACITY];
extern const int16_t g_inflightOptionsFocusPage0X[INFLIGHT_OPTIONS_PAGE0_FOCUS_COUNT];
extern const int16_t g_inflightOptionsFocusPage0Y[INFLIGHT_OPTIONS_PAGE0_FOCUS_COUNT];
extern const int16_t g_inflightOptionsFocusPage1X[INFLIGHT_OPTIONS_PAGE1_FOCUS_COUNT];
extern const int16_t g_inflightOptionsFocusPage1Y[INFLIGHT_OPTIONS_PAGE1_FOCUS_COUNT];
extern int16_t g_inflightOptionsPage;
extern Input* g_inflightOptionsPageInputs[INFLIGHT_OPTIONS_PAGE_COUNT];
extern uint8_t g_flightInterlaceEnabled;
extern int16_t g_inflightOptionsFocusIndex;

/* Declarations follow ascending original IDB address. */

#ifndef XW_MODERN
/* 0x44E490 */
XwShellSceneResult InflightOptions_Show(struct XwShellContext* shell);
#endif

/* 0x44F050 */
void InflightOptions_UpdateView(int time);

/* 0x44F110 */
void InflightOptions_SavePreferences(void);

/* 0x44F130 */
void InflightOptions_DrawPageBackground(Input* input, Rect* frame, Rect* clip, int16_t refresh);

/* 0x44F300 */
int16_t InflightOptions_UpdateVolumeSlider(Input* input, Rect* frame, Rect* clip, int16_t key, int leftEvent,
										   int rightEvent, int16_t x, int16_t y);

/* 0x44F380 */
void InflightOptions_HandleGeneralControl(Input* input, int context);

/* 0x44F800 */
void InflightOptions_DrawVolumeSlider(Input* input, Rect* frame, Rect* clip, int16_t refresh);

/* 0x44F890 */
int16_t InflightOptions_UpdateDetailSlider(Input* input, Rect* frame, Rect* clip, int16_t key, int leftEvent,
										   int rightEvent, int16_t x, int16_t y);

/* 0x44F910 */
void InflightOptions_HandleGraphicsControl(Input* input, int context);

/* 0x44FA80 */
void InflightOptions_DrawDetailSlider(Input* input, Rect* frame, Rect* clip, int16_t refresh);

/* 0x44FB10 */
void InflightOptions_HandleNavigation(Input* input, int context);

/* 0x44FC00 */
void InflightOptions_DrawNavigation(Input* input, Rect* frame, Rect* clip, int16_t refresh);

#ifdef __cplusplus
}
#endif

#endif
