#ifndef XW_FRONTEND_SHELL_H
#define XW_FRONTEND_SHELL_H

#ifdef __cplusplus
extern "C" {
#endif

#include "xw/landru_config.h"

#include <landru/actor.h>
#include <landru/font.h>
#include <landru/pal.h>
#include <landru/res.h>
#include <stddef.h>
#include <stdint.h>

struct XwLegacyMemoryConfig;
typedef struct XwShellContext XwShellContext;

typedef int32_t XwShellSceneId;

/* Modern scene entries schedule child tasks. Their owner obtains the scene ID
 * from Landru after resumption instead of consuming a synchronous return. */
#ifdef XW_MODERN
typedef void XwShellSceneResult;
#else
typedef XwShellSceneId XwShellSceneResult;
#endif

enum XwShellSceneIdValues {
	XW_SCENE_NO_EXIT_REQUESTED = -1,
	XW_SCENE_EXIT_SHELL = 0x0,
	XW_SCENE_INITIAL_PREVIOUS_SCENE = 0x1,
	XW_SCENE_FLIGHT_PROVING_GROUNDS = 0x2,
	XW_SCENE_FLIGHT_COMBAT = 0x3,
	XW_SCENE_FLIGHT_TOUR = 0x4,
	XW_SCENE_DIAGNOSTIC_MENU = 0x5,
	XW_SCENE_STARTUP_LOGO = 0x6,
	XW_SCENE_INTRO_TITLE_CRAWL = 0x7,
	XW_SCENE_TOUR_TITLE_CRAWL = 0x8,
	XW_SCENE_INTRO_OPENING = 0xA,
	XW_SCENE_INTRO_FLEET_ATTACK = 0xB,
	XW_SCENE_INTRO_IMPERIAL_BRIDGE = 0xD,
	XW_SCENE_INTRO_REBEL_BRIDGE = 0xE,
	XW_SCENE_INTRO_HANGAR_LAUNCH = 0x11,
	XW_SCENE_INTRO_OSSHT7 = 0x14,
	XW_SCENE_INTRO_DOGFIGHT_HRC2 = 0x15,
	XW_SCENE_INTRO_DOGFIGHT_HRC3 = 0x16,
	XW_SCENE_INTRO_DOGFIGHT_HRC4 = 0x17,
	XW_SCENE_XWING_LOGO = 0x18,
	XW_SCENE_INTRO_CREDITS = 0x19,
	XW_SCENE_REGISTER_INITIAL = 0x1A,
	XW_SCENE_INTRO_FORMATION = 0x1B,
	XW_SCENE_REGISTER_RETURN = 0x1C,
	XW_SCENE_VICTORY_CREDITS = 0x1D,
	XW_SCENE_CONCOURSE = 0x1E,
	XW_SCENE_TRAINING_DEPART_INDEPENDENCE = 0x28,
	XW_SCENE_TRAINING_HYPERSPACE = 0x29,
	XW_SCENE_TRAINING_ARRIVE_FACILITY = 0x2A,
	XW_SCENE_TRAINING_RETURN_SHUTTLE = 0x2B,
	XW_SCENE_PROVING_GROUNDS_ROOM = 0x2D,
	XW_SCENE_COMBAT_DEPART_INDEPENDENCE = 0x32,
	XW_SCENE_COMBAT_HYPERSPACE = 0x33,
	XW_SCENE_COMBAT_ARRIVE_FACILITY = 0x34,
	XW_SCENE_COMBAT_RETURN_SHUTTLE = 0x35,
	XW_SCENE_COMBAT_SIMULATOR_ROOM = 0x3C,
	XW_SCENE_TOUR_DESK = 0x46,
	XW_SCENE_TOUR_DEPART_INDEPENDENCE = 0x50,
	XW_SCENE_TOUR_HYPERSPACE = 0x51,
	XW_SCENE_TOUR_ARRIVE_DEFIANCE = 0x52,
	XW_SCENE_TOUR_RETURN_INDEPENDENCE = 0x53,
	XW_SCENE_RESCUE_ARRIVE_SALVATION = 0x55,
	XW_SCENE_CAPTURE_ARRIVE_EXECUTOR = 0x56,
	XW_SCENE_FILM_ROOM = 0x5A,
	XW_SCENE_TECH_ROOM = 0x5F,
	XW_SCENE_BRIEFING_LEGACY_110 = 0x6E,
	XW_SCENE_BRIEFING_COMBAT = 0x6F,
	XW_SCENE_BRIEFING_TOUR = 0x70,
	XW_SCENE_DEBRIEF_PROVING_GROUNDS = 0x73,
	XW_SCENE_DEBRIEF_COMBAT = 0x74,
	XW_SCENE_DEBRIEF_TOUR = 0x75,
	XW_SCENE_REQUEST_COMBAT_LAUNCH = 0x78,
	XW_SCENE_REQUEST_TOUR_LAUNCH = 0x7A,
	XW_SCENE_UNIFORM_FROM_COMBAT_BRIEFING = 0x7D,
	XW_SCENE_UNIFORM_FROM_TOUR_BRIEFING = 0x7E,
	XW_SCENE_PILOT_LOG_FROM_COMBAT_BRIEFING = 0x7F,
	XW_SCENE_PILOT_LOG_FROM_TOUR_BRIEFING = 0x80,
	XW_SCENE_UNIFORM_FROM_REGISTER = 0x82,
	XW_SCENE_PILOT_LOG_FROM_REGISTER = 0x83,
	XW_SCENE_AWARD_CASE_FROM_COMBAT_BRIEFING = 0x87,
	XW_SCENE_AWARD_CASE_FROM_TOUR_BRIEFING = 0x88,
	XW_SCENE_AWARD_CASE_FROM_REGISTER = 0x89,
	XW_SCENE_DESTROY_STAR_DESTROYER_1 = 0x8C,
	XW_SCENE_DESTROY_STAR_DESTROYER_2 = 0x8D,
	XW_SCENE_DESTROY_STAR_DESTROYER_3 = 0x8E,
	XW_SCENE_DEATH_STAR_FIRE_1 = 0x96,
	XW_SCENE_DEATH_STAR_FIRE_2 = 0x97,
	XW_SCENE_DEATH_STAR_FIRE_3 = 0x98,
	XW_SCENE_DEATH_STAR_FIRE_4 = 0x99,
	XW_SCENE_DEATH_STAR_FIRE_5 = 0x9A,
	XW_SCENE_DEATH_STAR_COMPLETED = 0xA0,
	XW_SCENE_DEATH_STAR_HANGAR = 0xA1,
	XW_SCENE_DEATH_STAR_VADER_ARRIVAL = 0xA2,
	XW_SCENE_DEATH_STAR_COMPLETION_SPEECH = 0xA3,
	XW_SCENE_DEATH_STAR_TARKIN_SPEECH = 0xA4,
	XW_SCENE_DEATH_STAR_COMPLETION_FIRE_ORDER = 0xA5,
	XW_SCENE_DEATH_STAR_COMPLETION_DFIRE3 = 0xA6,
	XW_SCENE_DEATH_STAR_COMPLETION_DFIRE4 = 0xA7,
	XW_SCENE_DEATH_STAR_COMPLETION_PRISON = 0xA8,
	XW_SCENE_DEATH_STAR_DESTRUCTION = 0xAA,
	XW_SCENE_YAVIN_APPROACH = 0xAB,
	XW_SCENE_YAVIN_FILM_2 = 0xAC,
	XW_SCENE_YAVIN_HEADQUARTERS = 0xAD,
	XW_SCENE_SEND_PLANS_1 = 0xB4,
	XW_SCENE_SEND_PLANS_2 = 0xB5,
	XW_SCENE_SEND_PLANS_3 = 0xB6,
	XW_SCENE_SEND_PLANS_4 = 0xB7,
	XW_SCENE_SEND_PLANS_5 = 0xB8,
	XW_SCENE_SEND_PLANS_6 = 0xB9,
	XW_SCENE_RECOVER_PLANS_1 = 0xBA,
	XW_SCENE_RECOVER_PLANS_2 = 0xBB,
	XW_SCENE_RECOVER_PLANS_FLEET = 0xBC,
	XW_SCENE_RECOVER_PLANS_VADER = 0xBD,
	XW_SCENE_EMPIRE_ASSAULT_1 = 0xBE,
	XW_SCENE_EMPIRE_ASSAULT_2 = 0xBF,
	XW_SCENE_EMPIRE_ASSAULT_3 = 0xC0,
	XW_SCENE_PILOT_RESCUED = 0xDC,
	XW_SCENE_PILOT_CAPTURED = 0xDD,
	XW_SCENE_PILOT_TORTURE = 0xDE,
	XW_SCENE_PILOT_MEDICAL_RECOVERY = 0xE1,
	XW_SCENE_FUNERAL_INTERIOR = 0xE6,
	XW_SCENE_FUNERAL_EXTERIOR = 0xE7,
	XW_SCENE_AWARD_CEREMONY_1 = 0xF0,
	XW_SCENE_AWARD_CEREMONY_2 = 0xF1,
	XW_SCENE_AWARD_CEREMONY_3 = 0xF2,
	XW_SCENE_VICTORY_MEDAL_CEREMONY_1 = 0xF5,
	XW_SCENE_VICTORY_MEDAL_CEREMONY_2 = 0xF6,
	XW_SCENE_VICTORY_MEDAL_CEREMONY_3 = 0xF7,
	XW_SCENE_TOUR_RETURN_AWING = 0xFA,
	XW_SCENE_TOUR_RETURN_XWING = 0xFB,
	XW_SCENE_TOUR_RETURN_YWING = 0xFC,
	XW_SCENE_TOUR_RETURN_BWING = 0xFD,
	XW_SCENE_LEGACY_TRAINING_TRANSITION_260 = 0x104,
	XW_SCENE_LEGACY_TRAINING_TRANSITION_261 = 0x105,
	XW_SCENE_LEGACY_TRAINING_TRANSITION_262 = 0x106,
	XW_SCENE_TRAINING_LAUNCH_XWING = 0x107,
	XW_SCENE_TRAINING_LAUNCH_YWING = 0x108,
	XW_SCENE_TRAINING_LAUNCH_AWING = 0x109,
	XW_SCENE_LEGACY_TRAINING_TRANSITION_266 = 0x10A,
	XW_SCENE_TRAINING_LAUNCH_BWING = 0x10B,
	XW_SCENE_LEGACY_COMBAT_TRANSITION_270 = 0x10E,
	XW_SCENE_LEGACY_COMBAT_TRANSITION_271 = 0x10F,
	XW_SCENE_LEGACY_COMBAT_TRANSITION_272 = 0x110,
	XW_SCENE_COMBAT_LAUNCH_XWING = 0x111,
	XW_SCENE_COMBAT_LAUNCH_YWING = 0x112,
	XW_SCENE_COMBAT_LAUNCH_AWING = 0x113,
	XW_SCENE_LEGACY_COMBAT_TRANSITION_276 = 0x114,
	XW_SCENE_COMBAT_LAUNCH_BWING = 0x115,
	XW_SCENE_LEGACY_TOUR_TRANSITION_281 = 0x119,
	XW_SCENE_TOUR_LAUNCH_BWING = 0x11A,
	XW_SCENE_LEGACY_TOUR_TRANSITION_283 = 0x11B,
	XW_SCENE_LEGACY_TOUR_TRANSITION_284 = 0x11C,
	XW_SCENE_LEGACY_TOUR_TRANSITION_285 = 0x11D,
	XW_SCENE_TOUR_LAUNCH_XWING = 0x11E,
	XW_SCENE_TOUR_LAUNCH_YWING = 0x11F,
	XW_SCENE_TOUR_LAUNCH_AWING = 0x120,
	XW_SCENE_TRAINING_RETURN_AWING = 0x122,
	XW_SCENE_TRAINING_RETURN_XWING = 0x123,
	XW_SCENE_TRAINING_RETURN_YWING = 0x124,
	XW_SCENE_TRAINING_RETURN_BWING = 0x128,
	XW_SCENE_COMBAT_RETURN_AWING = 0x12C,
	XW_SCENE_COMBAT_RETURN_XWING = 0x12D,
	XW_SCENE_COMBAT_RETURN_YWING = 0x12E,
	XW_SCENE_COMBAT_RETURN_BWING = 0x132,
	XW_SCENE_TRAINING_RESULTS_AWING = 0x136,
	XW_SCENE_TRAINING_RESULTS_XWING = 0x137,
	XW_SCENE_TRAINING_RESULTS_YWING = 0x138,
	XW_SCENE_TRAINING_RESULTS_BWING = 0x139,
	XW_SCENE_FLIGHT_REPLAY = 0x15E,
	XW_SCENE_FLIGHT_RESUME = 0x15F,
	XW_SCENE_INFLIGHT_MAP = 0x168,
	XW_SCENE_INFLIGHT_BRIEFING = 0x169,
	XW_SCENE_INFLIGHT_DAMAGE_CONTROL = 0x16A,
	XW_SCENE_INFLIGHT_OPTIONS = 0x16B,
	XW_SCENE_IMPERIAL_DRYDOCK_1 = 0x190,
	XW_SCENE_IMPERIAL_DRYDOCK_2 = 0x191,
	XW_SCENE_IMPERIAL_DRYDOCK_3 = 0x192,
	XW_SCENE_YAVIN_DEPARTURE_1 = 0x19A,
	XW_SCENE_YAVIN_DEPARTURE_2 = 0x19B,
	XW_SCENE_GHORIN_1 = 0x1A4,
	XW_SCENE_GHORIN_2 = 0x1A5,
	XW_SCENE_GHORIN_3 = 0x1A6,
	XW_SCENE_GHORIN_4 = 0x1A7,
	XW_SCENE_GHORIN_5 = 0x1A8,
	XW_SCENE_GHORIN_6 = 0x1A9,
	XW_SCENE_RAMMING_ATTACK_1 = 0x1AE,
	XW_SCENE_RAMMING_ATTACK_2 = 0x1AF,
	XW_SCENE_RAMMING_ATTACK_3 = 0x1B0,
	XW_SCENE_HOTH_1 = 0x1F4,
	XW_SCENE_HOTH_2 = 0x1F5,
	XW_SCENE_HOTH_3 = 0x1F6,
	XW_SCENE_BWING_ARRIVAL_1 = 0x1FE,
	XW_SCENE_BWING_ARRIVAL_2 = 0x1FF,
	XW_SCENE_IMPERIAL_PROBES_1 = 0x208,
	XW_SCENE_IMPERIAL_PROBES_2 = 0x209,
	XW_SCENE_IMPERIAL_PROBES_3 = 0x20A,
	XW_SCENE_INTRO_SUNSHOT = 0x20B,
	XW_SCENE_FUNERAL_PLANET = 0x20C
};

/* Original IDB size: 44 bytes. */
struct XwShellContext {
	/* IDB +0x0 */
	ResFile* resourceFile;
	/* IDB +0x4 */
	Palette* standardPalette;
	/* IDB +0x8 */
	Actor* icons;
	/* IDB +0xC */
	Actor* cursors;
	/* IDB +0x10 */
	FontStruct* font6;
	/* IDB +0x14 */
	FontStruct* font8;
	/* IDB +0x18 */
	FontStruct* font12;
	/* IDB +0x1C */
	FontStruct* font18;
	/* IDB +0x20: XwShellSceneId value. Storage width preserved from the executable; scene IDs include
	 * explicit control sentinels. */
	XwShellSceneId currentScene;
	/* IDB +0x24: XwShellSceneId value. Storage width preserved from the executable; scene IDs include
	 * explicit control sentinels. */
	XwShellSceneId lastScene;
	/* IDB +0x28 */
	int suddenEnd;
};

enum {
	XW_SHELL_MISSION_NAME_CAPACITY = 10,
	XW_SHELL_STREAM_CHANNEL = 1,
	XW_SHELL_STREAM_BUFFER_BYTES = 512000,
	XW_SHELL_STREAM_PREFETCH_BYTES = 256000
};

extern char g_shellMissionName[XW_SHELL_MISSION_NAME_CAPACITY];
extern int16_t g_installDriveLetter;

/* Declarations follow ascending original IDB address. */

extern XwShellContext* g_shellContext;

/* 0x4A57D0 */
XwShellSceneResult shell_Shell(XwShellSceneId scene, struct XwLegacyMemoryConfig* memory);

#ifdef __cplusplus
}
#endif

#endif
