#ifndef XW_FLIGHT_REPLAY_REPLAYIO_H
#define XW_FLIGHT_REPLAY_REPLAYIO_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

enum { REPLAYIO_SPOOL_PATH_CAPACITY = 32 };

enum { REPLAYIO_PANEL_IMAGE, REPLAYIO_PANEL_MASK, REPLAYIO_PANEL_PALETTE, REPLAYIO_PANEL_RESOURCE_COUNT };

enum {
	REPLAYIO_CAMERA_SPRITE_COUNT = 38,
	REPLAYIO_PANEL_PALETTE_COUNT = 64,
	REPLAYIO_LIVE_LOW_TOP = 17,
	REPLAYIO_LIVE_HIGH_TOP = 40,
	REPLAYIO_LIVE_LOW_HEIGHT = 135,
	REPLAYIO_LIVE_HIGH_HEIGHT = 325,
	REPLAYIO_FILM_LOW_LEFT = 14,
	REPLAYIO_FILM_LOW_TOP = 8,
	REPLAYIO_FILM_LOW_RIGHT = 306,
	REPLAYIO_FILM_LOW_BOTTOM = 131,
	REPLAYIO_FILM_LOW_HEIGHT = 123,
	REPLAYIO_FILM_HIGH_TOP = 19,
	REPLAYIO_FILM_HIGH_RIGHT = 611,
	REPLAYIO_FILM_HIGH_BOTTOM = 315,
	REPLAYIO_FILM_HIGH_HEIGHT = 295,
	REPLAYIO_FOOTER_TOP = 456
};

enum {
	REPLAYIO_SNAPSHOT_OBJECT_TABLE = 0,
	REPLAYIO_SNAPSHOT_MISSION_OBJECTS = 1,
	REPLAYIO_SNAPSHOT_CRAFT_TABLE = 2,
	REPLAYIO_SNAPSHOT_WARHEAD_GUIDANCE_TABLE = 3,
	REPLAYIO_SNAPSHOT_MISSION_ELAPSED_CLOCK = 4,
	REPLAYIO_SNAPSHOT_MISSION_COUNTDOWN_CLOCK = 5,
	REPLAYIO_SNAPSHOT_MISSION_HEADER = 6,
	REPLAYIO_SNAPSHOT_MISSION_FLIGHT_GROUP_STATES = 7,
	REPLAYIO_SNAPSHOT_MISSION_RUNTIME_STATE = 8,
	REPLAYIO_SNAPSHOT_PLAYER_FLIGHT_STATE = 9,
	REPLAYIO_SNAPSHOT_FLIGHT_CAMERA = 10,
	REPLAYIO_SNAPSHOT_FIELD_62D12A = 11,
	REPLAYIO_SNAPSHOT_FIELD_62D0E2 = 12,
	REPLAYIO_SNAPSHOT_FIELD_62D118 = 13,
	REPLAYIO_SNAPSHOT_TARGET_HIGHLIGHT_OBJECT_AND_BLINK_BITS = 14,
	REPLAYIO_SNAPSHOT_TARGET_HIGHLIGHT_BLINK_TICKS = 15,
	REPLAYIO_SNAPSHOT_FLIGHT_GLOBAL_COUNTDOWN_TIMERS = 16,
	REPLAYIO_SNAPSHOT_NEXT_DEBRIS_OBJECT_SLOT = 17,
	REPLAYIO_SNAPSHOT_SURFACE_CELL_DAMAGE_STATES = 18,
	REPLAYIO_SNAPSHOT_SURFACE_GUN_CELLS = 19,
	REPLAYIO_SNAPSHOT_SURFACE_GUN_CELL_COUNT = 20,
	REPLAYIO_SNAPSHOT_SURFACE_GUN_CELL_REFRESH_TICKS = 21,
	REPLAYIO_SNAPSHOT_BACKDROP_PACKED_DIRECTIONS = 22,
	REPLAYIO_SNAPSHOT_BACKDROP_MODEL_TYPES = 23,
	REPLAYIO_SNAPSHOT_BACKDROP_POSITIVE_Y_COUNT = 24,
	REPLAYIO_SNAPSHOT_BACKDROP_NEGATIVE_Y_COUNT = 25,
	REPLAYIO_SNAPSHOT_BACKDROP_POSITIVE_Z_COUNT = 26,
	REPLAYIO_SNAPSHOT_BACKDROP_NEGATIVE_Z_COUNT = 27,
	REPLAYIO_SNAPSHOT_BACKDROP_POSITIVE_X_COUNT = 28,
	REPLAYIO_SNAPSHOT_BACKDROP_NEGATIVE_X_COUNT = 29,
	REPLAYIO_SNAPSHOT_STAR_DENSITY = 30,
	REPLAYIO_SNAPSHOT_DEATH_STAR_SURFACE_MODE_ACTIVE = 31,
	REPLAYIO_SNAPSHOT_SURFACE_GOAL_CELL_HASH_SLOTS = 32,
	REPLAYIO_SNAPSHOT_SURFACE_GOAL_CELL_KEYS = 33,
	REPLAYIO_SNAPSHOT_BACKDROPS_ENABLED = 34,
	REPLAYIO_SNAPSHOT_DEBRIS_ENABLED = 35,
	REPLAYIO_SNAPSHOT_CRAFT_EXPLOSION_SPAWN_THRESHOLD = 36,
	REPLAYIO_SNAPSHOT_STARSHIP_DETAIL = 37,
	REPLAYIO_SNAPSHOT_SURFACE_OBJECT_DETAIL_LIMIT = 38,
	REPLAYIO_SNAPSHOT_TRENCH_OBJECT_DETAIL_LIMIT = 39,
	REPLAYIO_SNAPSHOT_DEATH_STAR_DETAIL_LEVEL = 40,
	REPLAYIO_SNAPSHOT_HYPERSPACE_EFFECT_OBJECT_COUNT = 41,
	REPLAYIO_SNAPSHOT_SHIP_DETAIL_VALUE = 42,
	REPLAYIO_SNAPSHOT_SHIP_DETAIL_POLY_COUNT = 43,
	REPLAYIO_SNAPSHOT_DRAW_MARKINGS_FLAG = 44,
	REPLAYIO_SNAPSHOT_FLIGHT_GRAPHICS_DETAIL_PRESET = 45,
	REPLAYIO_SNAPSHOT_MISSION_CHEAT_OPTIONS_USED = 46,
	REPLAYIO_SNAPSHOT_FLIGHT_MUSIC_VOLUME = 47,
	REPLAYIO_SNAPSHOT_FLIGHT_MUSIC_ENABLED = 48,
	REPLAYIO_SNAPSHOT_FLIGHT_SFX_VOLUME = 49,
	REPLAYIO_SNAPSHOT_FLIGHT_SFX_ENABLED = 50,
	REPLAYIO_SNAPSHOT_FLIGHT_ENGINE_SOUND_ENABLED = 51,
	REPLAYIO_SNAPSHOT_FLIGHT_DIGITAL_SOUND_ENABLED = 52,
	REPLAYIO_SNAPSHOT_FLIGHT_VOICE_ENABLED = 53,
	REPLAYIO_SNAPSHOT_FLIGHT_REPLAY_DISK_CACHE_KB = 54,
	REPLAYIO_SNAPSHOT_FLIGHT_REPLAY_DISK_CACHE_ENABLED = 55,
	REPLAYIO_SNAPSHOT_UNLIMITED_WEAPONS_ENABLED = 56,
	REPLAYIO_SNAPSHOT_FLIGHT_INVULNERABILITY_ENABLED = 57,
	REPLAYIO_SNAPSHOT_FLIGHT_CRAFT_COLLISIONS_ENABLED = 58,
	REPLAYIO_SNAPSHOT_FLIGHT_HIGH_DETAIL_STARFIELD = 59,
	REPLAYIO_SNAPSHOT_FLIGHT_BACKDROPS_PREFERENCE = 60,
	REPLAYIO_SNAPSHOT_FLIGHT_DEBRIS_PREFERENCE = 61,
	REPLAYIO_SNAPSHOT_FLIGHT_MARKINGS_PREFERENCE = 62,
	REPLAYIO_SNAPSHOT_FLIGHT_STARFIGHTER_DETAIL = 63,
	REPLAYIO_SNAPSHOT_FLIGHT_STARSHIP_DETAIL = 64,
	REPLAYIO_SNAPSHOT_FLIGHT_DEATH_STAR_DETAIL = 65,
	REPLAYIO_SNAPSHOT_FLIGHT_ENGINE_GLOW_PREFERENCE = 66,
	REPLAYIO_SNAPSHOT_MODEL_TEXTURE_QUALITY = 67,
	REPLAYIO_SNAPSHOT_FLIGHT_BRIGHTNESS_SETTING = 68,
	REPLAYIO_SNAPSHOT_GATE_GUN_TIMER = 69,
	REPLAYIO_SNAPSHOT_PROVING_GROUNDS_CHECKPOINT_BLINK_TICKS = 70,
	REPLAYIO_SNAPSHOT_DYNAMIC_MUSIC_STATE = 71,
	REPLAYIO_SNAPSHOT_DYNAMIC_MUSIC_OUTCOME_LATCHED = 72,
	REPLAYIO_SNAPSHOT_DYNAMIC_MUSIC_TRACK_REMAINING_MS = 73,
	REPLAYIO_SNAPSHOT_SURFACE_VICTORY_EXIT_SECOND = 74,
	REPLAYIO_SNAPSHOT_SURFACE_SPECIAL_TARGET_HIT = 75,
	REPLAYIO_SNAPSHOT_SURFACE_SPECIAL_TARGET_COLLISION_MODE = 76,
	REPLAYIO_SNAPSHOT_TRENCH_SPECIAL_CELL_VOICE_PLAYED = 77,
	REPLAYIO_SNAPSHOT_DEATH_STAR_RENDER_OBJECT = 78,
	REPLAYIO_SNAPSHOT_DEATH_STAR_RENDER_CRAFT = 79,
	REPLAYIO_SNAPSHOT_BLOCK_COUNT = 80,
	REPLAYIO_SNAPSHOT_TABLE_COUNT = REPLAYIO_SNAPSHOT_BLOCK_COUNT + 1
};

enum {
	REPLAYIO_DISK_OBJECT_SIZE = 83,
	REPLAYIO_DISK_CRAFT_SIZE = 462,
	REPLAYIO_DISK_MISSION_OBJECT_SIZE = 15,
	REPLAYIO_DISK_WARHEAD_GUIDANCE_SIZE = 3,
	REPLAYIO_DISK_MISSION_CLOCK_SIZE = 8,
	REPLAYIO_DISK_MISSION_HEADER_SIZE = 206,
	REPLAYIO_DISK_FLIGHT_GROUP_STATE_SIZE = 20,
	REPLAYIO_DISK_MISSION_RUNTIME_SIZE = 306,
	REPLAYIO_DISK_PLAYER_SIZE = 180,
	REPLAYIO_DISK_CAMERA_SIZE = 405,
	REPLAYIO_DISK_COUNTDOWN_TIMERS_SIZE = 20,
	REPLAYIO_DISK_SURFACE_DAMAGE_SIZE = 16,
	REPLAYIO_DISK_SURFACE_GUN_SIZE = 6,
	REPLAYIO_DISK_FLIGHT_GROUP_SIZE = 148,
};

extern void* g_ReplaySnapshotBlockPointers[REPLAYIO_SNAPSHOT_TABLE_COUNT];
extern unsigned int g_ReplaySnapshotBlockSizes[REPLAYIO_SNAPSHOT_TABLE_COUNT];
extern uint16_t g_snapshotField62D0E2;
extern uint16_t g_snapshotField62D12A;

extern uint8_t g_replaySpoolMessagesSuppressed;
extern uint8_t g_ReplaySpoolEnabled;
extern uint8_t* g_replayCockpitResources[REPLAYIO_PANEL_RESOURCE_COUNT];

/* Declarations follow ascending original IDB address. */

/* 0x41EE50 */
int16_t replayio_copytosave(const char* filename);

/* 0x41EF40 */
int16_t replayio_copyfromsave(const char* filename);

/* 0x41F010 */
int16_t replayio_openreplayinputfile(void);

/* 0x41F090 */
int16_t replayio_spoolreplayinput(void);

/* 0x41F1B0 */
int16_t replayio_savereplaybuffer(void);

/* 0x41F220 */
int16_t replayio_restorereplaybuffer(void);

/* 0x41F280 */
void replayio_replayscreen(void);

/* 0x41FB00 */
void replayio_setreturnview(void);

#ifdef __cplusplus
}
#endif

#endif
