# Adapted from OpenXvT's application bundle and resource staging.
set(XW_VERSION "0.0.0-dev" CACHE STRING "OpenXW package version")
target_compile_definitions(xw PRIVATE OPENXW_VERSION="${XW_VERSION}")
set(XW_AERON_DEFAULTS "${CMAKE_SOURCE_DIR}/aeron/config/scene3d_defaults.yaml")
set(XW_DEFAULT_RESOURCES
    "${CMAKE_SOURCE_DIR}/resources/config.yaml"
    "${CMAKE_SOURCE_DIR}/resources/opt_alpha_overrides.yaml"
    "${CMAKE_SOURCE_DIR}/resources/gate_lights.yaml"
    "${CMAKE_SOURCE_DIR}/resources/ui-theme.yaml")
set(XW_UI_FONTS
    "${CMAKE_SOURCE_DIR}/resources/assets/fonts/menu.fnt"
    "${CMAKE_SOURCE_DIR}/resources/assets/fonts/menu.png")
add_dependencies(xw aeron_shaders xw_shaders)
set(XW_ALL_SHADER_OUTPUTS ${AERON_SHADER_OUTPUTS} ${XW_SHADER_OUTPUTS})

if(APPLE)
    set(XW_MACOS_BUILD_VERSION "1" CACHE STRING "macOS bundle build version")
    set(XW_MACOS_BUNDLE_IDENTIFIER "org.totallyopen.openxw" CACHE STRING "macOS bundle identifier")
    set_target_properties(xw PROPERTIES
        MACOSX_BUNDLE TRUE
        MACOSX_BUNDLE_INFO_PLIST "${CMAKE_SOURCE_DIR}/cmake/macos/Info.plist.in"
        INSTALL_RPATH "@executable_path/../Frameworks")
    set(XW_MACOS_ICON "${CMAKE_SOURCE_DIR}/cmake/macos/OpenXW.icns")
    target_sources(xw PRIVATE "${XW_MACOS_ICON}")
    set_source_files_properties("${XW_MACOS_ICON}" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
    target_sources(xw PRIVATE "${XW_AERON_DEFAULTS}" ${XW_DEFAULT_RESOURCES} ${XW_ALL_SHADER_OUTPUTS})
    set_source_files_properties("${XW_AERON_DEFAULTS}" PROPERTIES
        HEADER_FILE_ONLY TRUE MACOSX_PACKAGE_LOCATION Resources/resources/aeron)
    set_source_files_properties(${XW_DEFAULT_RESOURCES} PROPERTIES
        HEADER_FILE_ONLY TRUE
        MACOSX_PACKAGE_LOCATION Resources/resources)
    target_sources(xw PRIVATE ${XW_UI_FONTS})
    set_source_files_properties(${XW_UI_FONTS} PROPERTIES
        HEADER_FILE_ONLY TRUE MACOSX_PACKAGE_LOCATION Resources/resources/assets/fonts)
    set_source_files_properties(${XW_ALL_SHADER_OUTPUTS} PROPERTIES
        GENERATED TRUE MACOSX_PACKAGE_LOCATION Resources/shaders)

    # FSR shaders are generated by a separate Aeron target. Stage on every build
    # so shader-only changes are also reflected in the bundle without a relink.
    add_custom_target(xw_bundle_shaders ALL
        COMMAND "${CMAKE_COMMAND}"
            "-DXW_BUNDLE_CONTENT_DIR=$<TARGET_BUNDLE_CONTENT_DIR:xw>"
            "-DXW_SHADER_SOURCE_DIR=${CMAKE_BINARY_DIR}/shaders"
            -P "${CMAKE_SOURCE_DIR}/cmake/macos/StageBundle.cmake"
        DEPENDS aeron_shaders xw_shaders VERBATIM)
    add_dependencies(xw xw_bundle_shaders)
    install(TARGETS xw BUNDLE DESTINATION . COMPONENT Runtime)
    set(XW_PACKAGE_RESOURCE_DIR "OpenXW.app/Contents/Resources")
    set(XW_MACOS_DEPENDENCY_DIRS)
    foreach(prefix IN LISTS CMAKE_PREFIX_PATH)
        list(APPEND XW_MACOS_DEPENDENCY_DIRS "${prefix}/lib")
    endforeach()
    configure_file("${CMAKE_SOURCE_DIR}/cmake/macos/FixupBundle.cmake.in"
        "${CMAKE_CURRENT_BINARY_DIR}/FixupMacBundle.cmake" @ONLY)
    install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/FixupMacBundle.cmake" COMPONENT Runtime)
else()
    set(XW_PACKAGE_RESOURCE_DIR ".")
    add_custom_target(xw_resources
        COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:xw>/resources/aeron"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${XW_AERON_DEFAULTS}"
            "$<TARGET_FILE_DIR:xw>/resources/aeron/scene3d_defaults.yaml"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:xw>/resources/assets/fonts"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${XW_UI_FONTS}
            "$<TARGET_FILE_DIR:xw>/resources/assets/fonts"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${XW_DEFAULT_RESOURCES}
            "$<TARGET_FILE_DIR:xw>/resources"
        DEPENDS "${XW_AERON_DEFAULTS}" ${XW_DEFAULT_RESOURCES} ${XW_UI_FONTS} VERBATIM)
    add_dependencies(xw xw_resources)
    if(UNIX)
        set_target_properties(xw PROPERTIES INSTALL_RPATH "$ORIGIN/lib")
    endif()
    install(TARGETS xw RUNTIME DESTINATION . COMPONENT Runtime)
    install(FILES "${XW_AERON_DEFAULTS}" DESTINATION resources/aeron COMPONENT Runtime)
    install(FILES ${XW_DEFAULT_RESOURCES} DESTINATION resources COMPONENT Runtime)
    install(FILES ${XW_UI_FONTS} DESTINATION resources/assets/fonts COMPONENT Runtime)
    foreach(format IN LISTS AERON_SHADER_FORMATS)
        if(format STREQUAL "MSL")
            set(extension msl)
        elseif(format STREQUAL "DXIL")
            set(extension dxil)
        else()
            set(extension spv)
        endif()
        install(DIRECTORY "${CMAKE_BINARY_DIR}/shaders/" DESTINATION shaders
            COMPONENT Runtime FILES_MATCHING PATTERN "*.${extension}")
    endforeach()
endif()

install(FILES "${CMAKE_SOURCE_DIR}/README.md"
    DESTINATION "${XW_PACKAGE_RESOURCE_DIR}" COMPONENT Runtime)
install(FILES "${CMAKE_SOURCE_DIR}/aeron/LICENSE"
    DESTINATION "${XW_PACKAGE_RESOURCE_DIR}/licenses" RENAME Aeron.txt COMPONENT Runtime)
install(FILES "${CMAKE_SOURCE_DIR}/src/landru/LICENSE"
    DESTINATION "${XW_PACKAGE_RESOURCE_DIR}/licenses" RENAME Landru.txt COMPONENT Runtime)
foreach(license IN ITEMS "bc7enc/LICENSE" "fidelityfx-fsr3/LICENSE.txt"
        "libyaml/License" "cgltf/LICENSE" "stb/LICENSE" "dxmath/LICENSE" "dxtex/LICENSE")
    get_filename_component(library "${license}" DIRECTORY)
    install(FILES "${CMAKE_SOURCE_DIR}/aeron/third_party/${license}"
        DESTINATION "${XW_PACKAGE_RESOURCE_DIR}/licenses" RENAME "${library}.txt" COMPONENT Runtime)
endforeach()

if(XW_ENABLE_DEBUG_UI)
    install(FILES "${CMAKE_SOURCE_DIR}/aeron/third_party/imgui/LICENSE.txt"
        DESTINATION "${XW_PACKAGE_RESOURCE_DIR}/licenses" RENAME imgui.txt COMPONENT Runtime)
endif()

if(TARGET nuked_sc55_core)
    install(FILES "${CMAKE_SOURCE_DIR}/src/imuse/third_party/nuked-sc55/LICENSE"
        DESTINATION "${XW_PACKAGE_RESOURCE_DIR}/licenses" RENAME Nuked-SC55.txt COMPONENT Runtime)
endif()

if(WIN32)
    enable_language(RC)
    if(XW_VERSION MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)")
        set(XW_VERSION_MAJOR ${CMAKE_MATCH_1})
        set(XW_VERSION_MINOR ${CMAKE_MATCH_2})
        set(XW_VERSION_PATCH ${CMAKE_MATCH_3})
    else()
        set(XW_VERSION_MAJOR 0)
        set(XW_VERSION_MINOR 0)
        set(XW_VERSION_PATCH 0)
    endif()
    set(XW_WINDOWS_ICON "${CMAKE_SOURCE_DIR}/cmake/windows/openxw.ico")
    configure_file("${CMAKE_SOURCE_DIR}/cmake/windows/xw.rc.in"
        "${CMAKE_CURRENT_BINARY_DIR}/xw.rc" @ONLY)
    target_sources(xw PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/xw.rc")
endif()
