#ifndef XW_FLIGHT_HUD_MSG_H
#define XW_FLIGHT_HUD_MSG_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

struct CraftData;
typedef struct XwHudInFlightMessageRecord XwHudInFlightMessageRecord;

typedef uint16_t XwFlightMessageId;

enum { XW_MSG_READY_QUEUE_CAPACITY = 11, XW_MSG_TEMPLATE_COUNT = 175 };

enum { XW_MSG_PANE_DEFAULT = 0, XW_MSG_PANE_MEDIUM = 1, XW_MSG_PANE_LONG = 2 };

enum {
	XW_MSG_LONG_DURATION_TICKS = 2832,
	XW_MSG_MEDIUM_DURATION_TICKS = 1652,
	XW_MSG_QUEUED_DURATION_TICKS = 472,
	XW_MSG_DEFAULT_DURATION_TICKS = 944
};

enum {
	XW_MSG_STRIP_LOW_RESOLUTION_TOP = 190,
	XW_MSG_STRIP_HIGH_RESOLUTION_TOP = 456,
	XW_MSG_STRIP_LEFT_MARGIN = 2,
	XW_MSG_STRIP_TOP_MARGIN = 1,
	XW_MSG_BORDER_COLOR = 0x1F,
	XW_MSG_BACKGROUND_COLOR = 0x19,
	XW_MSG_SHADOW_COLOR = 0x40,
	XW_MSG_TEXT_COLOR = 0x49
};

enum { XW_MSG_MAX_PENDING_MESSAGES = XW_MSG_READY_QUEUE_CAPACITY - 2 };

enum { XW_MSG_RADIO_RESPONSE_RANDOM_BIT = 0x8000 };

enum { XW_MSG_ARGUMENT_COUNT = 4, XW_MSG_DYNAMIC_STRING_COUNT = 4, XW_MSG_DYNAMIC_STRING_FLAG = 0x8000 };

enum XwFlightMessageIdValues {
	XW_MSG_VERSION_BANNER = 0x0,
	XW_MSG_MISSION_PAUSED = 0x1,
	XW_MSG_MISSION_RESUMED = 0x2,
	XW_MSG_LASER_CANNONS_ARMED = 0x3,
	XW_MSG_ION_CANNONS_ARMED = 0x4,
	XW_MSG_WARHEAD_LAUNCHERS_ARMED = 0x5,
	XW_MSG_WARHEAD_LAUNCHERS_SINGLE_FIRE = 0x6,
	XW_MSG_WARHEAD_LAUNCHERS_DUAL_FIRE = 0x7,
	XW_MSG_PROTON_TORPEDO = 0x8,
	XW_MSG_CONCUSSION_MISSILE = 0x9,
	XW_MSG_CANNONS_SINGLE_FIRE = 0xA,
	XW_MSG_CANNONS_DUAL_FIRE = 0xB,
	XW_MSG_CANNONS_LINKED_FIRE = 0xC,
	XW_MSG_DEFLECTOR_SHIELD_DISTRIBUTION = 0xD,
	XW_MSG_SHIELDS_FULL_FORWARD = 0xE,
	XW_MSG_SHIELDS_EVEN_FORWARD_AND_AFT = 0xF,
	XW_MSG_SHIELDS_FULL_AFT = 0x10,
	XW_MSG_LASER_RECHARGE_RATE = 0x11,
	XW_MSG_SHIELD_RECHARGE_RATE = 0x12,
	XW_MSG_POWER_TO_ENGINES_MAXIMUM = 0x13,
	XW_MSG_POWER_TO_ENGINES_MINIMUM = 0x14,
	XW_MSG_RECHARGING_NORMAL = 0x15,
	XW_MSG_RECHARGING_INCREASED = 0x16,
	XW_MSG_RECHARGING_MAXIMUM = 0x17,
	XW_MSG_SUBSYSTEM_STATUS = 0x18,
	XW_MSG_SUBSYSTEM_DAMAGED_AND_INOPERATIVE = 0x19,
	XW_MSG_SUBSYSTEM_REPAIRED = 0x1A,
	XW_MSG_SUBSYSTEM_ENGINE = 0x1B,
	XW_MSG_SUBSYSTEM_FLIGHT_CONTROL = 0x1C,
	XW_MSG_SUBSYSTEM_LASER = 0x1D,
	XW_MSG_SUBSYSTEM_ION_CANNON = 0x1E,
	XW_MSG_SUBSYSTEM_TORPEDO_LAUNCHER = 0x1F,
	XW_MSG_SUBSYSTEM_MISSILE_LAUNCHER = 0x20,
	XW_MSG_SUBSYSTEM_TARGETING_COMPUTER = 0x21,
	XW_MSG_SUBSYSTEM_AUTO_EJECTION = 0x22,
	XW_MSG_SUBSYSTEM_DEFLECTOR_SHIELD = 0x23,
	XW_MSG_SUBSYSTEM_HYPERDRIVE = 0x24,
	XW_MSG_GRAPHICS_DETAIL_LEVEL = 0x25,
	XW_MSG_DETAIL_LOWEST = 0x26,
	XW_MSG_DETAIL_LOW = 0x27,
	XW_MSG_DETAIL_HIGH = 0x28,
	XW_MSG_DETAIL_HIGHEST = 0x29,
	XW_MSG_HYPERSPACE_JUMP_PREPARING = 0x2A,
	XW_MSG_HYPERSPACE_JUMP_ABORTED = 0x2B,
	XW_MSG_HYPERSPACE_JUMP_COMPLETED = 0x2C,
	XW_MSG_SENSORS_NEW_CRAFT_SINGULAR = 0x2D,
	XW_MSG_SENSORS_NEW_CRAFT_PLURAL = 0x2E,
	XW_MSG_SPACE_PADDING = 0x2F,
	XW_MSG_PROVING_GROUNDS_LEVEL_COMPLETED = 0x30,
	XW_MSG_BONUS_POINTS_AWARDED = 0x31,
	XW_MSG_ENEMY_MISSILE_LOCK_TARGET_PROMPT = 0x32,
	XW_MSG_INCOMING_MISSILE_TARGET_PROMPT = 0x33,
	XW_MSG_MISSILE_TARGETED = 0x34,
	XW_MSG_HYPERSPACE_PATH_BLOCKED = 0x35,
	XW_MSG_REPLAY_CAMERA_ON = 0x36,
	XW_MSG_REPLAY_CAMERA_OFF = 0x37,
	XW_MSG_REPLAY_CAMERA_START_FAILED = 0x38,
	XW_MSG_CAMERA_FOOTAGE_SAVING = 0x39,
	XW_MSG_CAMERA_FOOTAGE_SAVED = 0x3A,
	XW_MSG_CAMERA_FILM_EXHAUSTED = 0x3B,
	XW_MSG_CAMERA_FOOTAGE_LOADING = 0x3C,
	XW_MSG_NO_FILM_RECORDED = 0x3D,
	XW_MSG_FILM_END_REACHED = 0x3E,
	XW_MSG_FILM_STARTED = 0x3F,
	XW_MSG_FILM_STOPPED = 0x40,
	XW_MSG_FILM_ADVANCE_ON = 0x41,
	XW_MSG_FILM_ADVANCE_OFF = 0x42,
	XW_MSG_FILM_REWOUND = 0x43,
	XW_MSG_CAMERA_FOLLOW_MODE = 0x44,
	XW_MSG_CAMERA_FREE_MODE = 0x45,
	XW_MSG_MISSION_TWO_MINUTES_REMAINING = 0x46,
	XW_MSG_MISSION_ONE_MINUTE_REMAINING = 0x47,
	XW_MSG_MISSION_TIME_EXPIRED_HYPERSPACE = 0x48,
	XW_MSG_HANGAR_TRACTOR_BEAM_END_MISSION_PROMPT = 0x49,
	XW_MSG_MISSION_OBJECTIVES_FAILED_RETURN_TO_BASE = 0x4A,
	XW_MSG_ENTER_FILENAME_PROMPT = 0x4B,
	XW_MSG_FILE_EXISTS_REPLACE_PROMPT = 0x4C,
	XW_MSG_REPLAY_CLIP_SAVED = 0x4D,
	XW_MSG_REPLAY_CLIP_NOT_SAVED = 0x4E,
	XW_MSG_FILE_ERROR = 0x4F,
	XW_MSG_ENGINE_THROTTLE_SETTING = 0x50,
	XW_MSG_THROTTLE_NO_POWER = 0x51,
	XW_MSG_THROTTLE_ONE_THIRD_POWER = 0x52,
	XW_MSG_THROTTLE_TWO_THIRDS_POWER = 0x53,
	XW_MSG_THROTTLE_FULL_POWER = 0x54,
	XW_MSG_COMBAT_DISPLAY_MODE = 0x55,
	XW_MSG_DISPLAY_TARGETING_MODE = 0x56,
	XW_MSG_DISPLAY_IDENTIFICATION_MODE = 0x57,
	XW_MSG_SFOILS_OPENING = 0x58,
	XW_MSG_SFOILS_CLOSING = 0x59,
	XW_MSG_SFOILS_POSITION_REACHED = 0x5A,
	XW_MSG_SFOILS_OPEN_POSITION = 0x5B,
	XW_MSG_SFOILS_CLOSED_POSITION = 0x5C,
	XW_MSG_TRANSFER_SHIELDS_TO_LASERS = 0x5D,
	XW_MSG_TRANSFER_LASERS_TO_SHIELDS = 0x5E,
	XW_MSG_CRAFT_EVENT_NUMBERED = 0x5F,
	XW_MSG_CRAFT_EVENT_UNNUMBERED = 0x60,
	XW_MSG_CRAFT_ENTERED_HYPERSPACE = 0x61,
	XW_MSG_CRAFT_DESTROYED = 0x62,
	XW_MSG_CRAFT_DISABLED = 0x63,
	XW_MSG_CRAFT_REPAIRED = 0x64,
	XW_MSG_CRAFT_CAPTURED = 0x65,
	XW_MSG_CRAFT_DOCKED = 0x66,
	XW_MSG_CRAFT_TARGETED = 0x67,
	XW_MSG_TARGET_EVENT_NUMBERED = 0x68,
	XW_MSG_TARGET_EVENT_UNNUMBERED = 0x69,
	XW_MSG_WARHEAD_LAUNCHER_EMPTY = 0x6A,
	XW_MSG_WARHEAD_FIRED_SINGULAR = 0x6B,
	XW_MSG_WARHEAD_FIRED_PLURAL = 0x6C,
	XW_MSG_CRAFT_ENTERED_HANGAR = 0x6D,
	XW_MSG_RADIO_ACKNOWLEDGED_NUMBERED = 0x6E,
	XW_MSG_RADIO_ACKNOWLEDGED_UNNUMBERED = 0x6F,
	XW_MSG_RADIO_HEADING_HOME = 0x70,
	XW_MSG_RADIO_COMING_TO_YOUR_AID = 0x71,
	XW_MSG_RADIO_MAKING_EVASIVE_MANEUVER = 0x72,
	XW_MSG_RADIO_WAITING_FOR_ORDERS = 0x73,
	XW_MSG_RADIO_PROCEEDING_WITH_MISSION = 0x74,
	XW_MSG_RADIO_USING_DESIGNATED_TARGET = 0x75,
	XW_MSG_RADIO_IGNORING_TARGET = 0x76,
	XW_MSG_CRAFT_DOCKING_OPERATION_COMPLETE = 0x77,
	XW_MSG_CRAFT_REPORT_NUMBERED = 0x78,
	XW_MSG_CRAFT_REPORT_UNNUMBERED = 0x79,
	XW_MSG_REPORT_HOLDING_STEADY = 0x7A,
	XW_MSG_REPORT_LEADING_FORMATION = 0x7B,
	XW_MSG_REPORT_FOLLOWING_IN_FORMATION = 0x7C,
	XW_MSG_REPORT_PATROLLING_FOR_ENEMY = 0x7D,
	XW_MSG_REPORT_PATROLLING_FOR_ESCORTERS = 0x7E,
	XW_MSG_REPORT_PATROLLING_FOR_TRANSPORTS = 0x7F,
	XW_MSG_REPORT_PATROLLING_FOR_FREIGHTERS = 0x80,
	XW_MSG_REPORT_PATROLLING_FOR_STARSHIPS = 0x81,
	XW_MSG_REPORT_PATROLLING_FOR_SATELLITES = 0x82,
	XW_MSG_REPORT_SETTING_UP_ATTACK_RUN = 0x83,
	XW_MSG_REPORT_ATTACKING_TARGET = 0x84,
	XW_MSG_REPORT_EVASIVE_MANEUVER = 0x85,
	XW_MSG_REPORT_FOLLOWING_FLIGHT_LEADER = 0x86,
	XW_MSG_REPORT_SEEKING_ENEMY_TO_DISABLE = 0x87,
	XW_MSG_REPORT_SEEKING_TRANSPORTS_TO_DISABLE = 0x88,
	XW_MSG_REPORT_SEEKING_FREIGHTERS_TO_DISABLE = 0x89,
	XW_MSG_REPORT_SEEKING_STARSHIPS_TO_DISABLE = 0x8A,
	XW_MSG_REPORT_FLYING_CLOSE_ESCORT = 0x8B,
	XW_MSG_REPORT_FLYING_LOOSE_ESCORT = 0x8C,
	XW_MSG_REPORT_FOLLOWING_CLOSE_ESCORT = 0x8D,
	XW_MSG_REPORT_FOLLOWING_LOOSE_ESCORT = 0x8E,
	XW_MSG_REPORT_SEEKING_CRAFT_TO_BOARD = 0x8F,
	XW_MSG_REPORT_SEEKING_CRAFT_TO_CAPTURE = 0x90,
	XW_MSG_REPORT_DOCKING_OPERATION = 0x91,
	XW_MSG_REPORT_FLYING_TO_RENDEZVOUS = 0x92,
	XW_MSG_REPORT_AWAITING_BOARDING_CRAFT = 0x93,
	XW_MSG_REPORT_DISABLED_AWAITING_RESCUE = 0x94,
	XW_MSG_REPORT_FLYING_HOME = 0x95,
	XW_MSG_REPORT_ENTERING_HANGAR = 0x96,
	XW_MSG_REPORT_EXITING_HANGAR = 0x97,
	XW_MSG_REPORT_ENTERING_HYPERSPACE = 0x98,
	XW_MSG_REPORT_EXITING_HYPERSPACE = 0x99,
	XW_MSG_REPORT_HOLDING_STATION = 0x9A,
	XW_MSG_REPORT_PATROLLING_AREA = 0x9B,
	XW_MSG_REPORT_WAITING_FOR_CRAFT_RETURN = 0x9C,
	XW_MSG_REPORT_WAITING_FOR_CRAFT_LAUNCH = 0x9D,
	XW_MSG_REPORT_WAITING_FOR_DOCKING_CRAFT = 0x9E,
	XW_MSG_REPORT_AWAITING_ORDERS = 0x9F,
	XW_MSG_MISSION_COMPLETE = 0xA0,
	XW_MSG_MISSION_COMPLETION_TEXT = 0xA1,
	XW_MSG_PLAYER_EJECTED_SAFELY = 0xA2,
	XW_MSG_PREVIOUS_LEVEL_POINTS_AWARDED = 0xA3,
	XW_MSG_SIMULATION_ENTRY_UNAVAILABLE = 0xA4,
	XW_MSG_SUBSYSTEM_LAUNCHER_GENERIC = 0xA5,
	XW_MSG_SUBSYSTEM_CANNON_GENERIC = 0xA6,
	XW_MSG_PLAYER_DIED = 0xA7,
	XW_MSG_EXHAUST_PORT_DIRECT_HIT = 0xA8,
	XW_MSG_ENTERING_HYPERSPACE = 0xA9,
	XW_MSG_UNIDENTIFIED_CRAFT_NAME = 0xAA,
	XW_MSG_CRAFT_IDENTIFIED = 0xAB,
	XW_MSG_MATCHING_TARGET_SPEED = 0xAC,
	XW_MSG_MATCHING_TARGET_SPEED_MAX_THROTTLE = 0xAD,
	XW_MSG_FILM_SAVING = 0xAE,
	XW_MSG_INACTIVE = 0xFFFF
};

/* Original IDB size: 90 bytes. */
struct XwHudInFlightMessageRecord {
	/* IDB +0x0: Message string ID; 0xFFFF marks an inactive pane. */
	uint16_t stateOrMessageId;
	/* IDB +0x2: Snapshot of mission clock subsecondTicks, copied by MSG_messageprintf. */
	int16_t clockSubsecondTicks;
	/* IDB +0x4 */
	uint8_t clockSeconds;
	/* IDB +0x5 */
	uint8_t clockMinutes;
	/* IDB +0x6: Snapshot of mission clock hours. */
	uint8_t clockHours;
	/* IDB +0x7: Message class derived from the leading control byte: 0 default, 1 queued, 2 priority; selects
	 * replacement behavior and display duration. */
	uint8_t paneType;
	/* IDB +0x8: Initialized to 0 by MSG_messageprintf; consumer semantics unresolved. */
	uint8_t field_08;
	/* IDB +0x9: Initialized to 1 by MSG_messageprintf; consumer semantics unresolved. */
	uint8_t field_09;
	/* IDB +0xA: Up to 80 bytes including inline palette controls; renderer is bounded to 80 bytes. */
	char text[80];
};

extern const char* const g_flightMessageTemplates[XW_MSG_TEMPLATE_COUNT];
extern uint16_t g_msgArgTable[XW_MSG_ARGUMENT_COUNT];
extern uint8_t g_messageDynamicStringCursor;
extern XwHudInFlightMessageRecord g_readyMessagePaneQueue[XW_MSG_READY_QUEUE_CAPACITY];
extern uint8_t g_readyMessageQueueCount;
extern const char* g_messageDynamicStrings[XW_MSG_DYNAMIC_STRING_COUNT];

/* Declarations follow ascending original IDB address. */

/* 0x411CF0 */
void msg_messageinit(void);

/* 0x411DB0 */
void msg_messageprintf(XwFlightMessageId messageId);

/* 0x412090 */
/* Requires a pending count from 0 through XW_MSG_MAX_PENDING_MESSAGES. */
void msg_movecurrentmessageinqueue(void);

/* 0x4120F0 */
void msg_getmessagefromqueue(void);

/* 0x412130 */
void msg_messagedisplay(void);

/* 0x4121B0 */
void msg_readymessage(void);

/* 0x412240 */
void msg_completemessage(int16_t paneType, char lastCharacter);

/* 0x4122F0 */
void msg_messageupdate(void);

/* 0x4123A0 */
void msg_clearmessagequeue(void);

/* 0x4123C0 */
void msg_reportfgcreation(uint16_t flightGroupIndex, uint16_t craftTypeIndex);

/* 0x412500 */
/* Requires a valid argument slot and dynamic-string cursor. Borrows value without copying it. */
void msg_addmessageptr(uint16_t slot, const char* value);

/* 0x412550 */
void msg_craftmessage(uint16_t objectIndex, const struct CraftData* craft, XwFlightMessageId messageTextId);

/* 0x412610 */
void msg_radiomessage(const struct CraftData* craft, XwFlightMessageId commandTextId);

/* 0x412770 */
void msg_reportmessage(const struct CraftData* craft, XwFlightMessageId reportTextId);

#ifdef __cplusplus
}
#endif

#endif
